module.exports = {
    home_title: 'POC REACT APP',
    error_mdp: 'Le mot de passe est incorrect.',
    error_email: 'Identifiants est incorrect.',
    not_found: 'User not found',
    is_exist: 'Identifiants deja utilise',
    account_not_active: 'plase verify your email and activate your account',
    find: 'Rechercher',
    auth: {
        signTitle: 'Connexion',
        signupTitle: 'Création',
        sign: 'Authentification',
        signUp: 'Création compte',
        succes: 'Ajout avec success',
        username: 'Username',
        email: 'Email',
        password: 'Mot de passe',
        user_adm: 'Administrateur',
        user_usr: 'Utilisateur',
        role: 'Rôle',
        profil: 'Profile',
        account_type: 'Type Compte',
        edit: 'Modifier',
        identification: 'Identifiant',
    },
    entity: {
        signTitle: 'Connexion',
        signupTitle: 'Création',
        sign: 'Authentification',
        signUp: 'Création Entity',
        succes: 'Ajout avec success',
        identification: 'Entity2',
        username: 'Entity1',
        email: 'Entity2',
        password: 'Entity3',
        user_adm: 'Administrateur',
        user_usr: 'Utilisateur',
        role: 'Rôle',
        profil: 'Profile',
        account_type: 'Type Compte',
        edit: 'Modifier',
    },
};